name: Build and publish image to Docker hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build -t ouitoulia/naus-emporos:latest .
      - name: publish
        run: |
          docker login -u ouitoulia -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ouitoulia/naus-emporos:latest