name: Build and publish images to Docker hub

on:
  repository_dispatch:
    name: "Build and publish images to Docker hub"
    types: [trigger-workflow]

jobs:
  publish_image:
    name: "Build and publish images to Docker hub"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 1.x

      - name: Fixup git permissions
        # https://github.com/actions/checkout/issues/766
        shell: bash
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Get Ouitoulia latest version
        id: data
        run: |
          echo "ouitoulia_tag=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
          echo "ouitoulia_minor=$(echo "${{ github.event.client_payload.version }}" | cut -d '.' -f1,2)" >> $GITHUB_ENV
        shell: bash

      - name: Fix version in Dockerfile
        run: |
          # Modifico la versione nel Dockerfile con ${{ env.ouitoulia_tag }}
          sed -i "s/ENV OUITOULIA_VERSION .*/ENV OUITOULIA_VERSION ${{ env.ouitoulia_tag }}/" Dockerfile
          # git add Dockerfile
          # git commit -m "Update Dockerfile version ${{ env.ouitoulia_tag }}"
          # git push origin
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish
        run: |
          docker login -u ouitoulia -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker buildx create --use
          docker buildx build --provenance=true --sbom=true -t ouitoulia/naus-emporos:${{ env.ouitoulia_tag }} --push .
          docker buildx build --provenance=true --sbom=true -t ouitoulia/naus-emporos:${{ env.ouitoulia_minor }} --push .
          docker buildx build --provenance=true --sbom=true -t ouitoulia/naus-emporos:latest --push .
        shell: bash
