name: Build and publish image to Docker hub
on:
  workflow_run:
    workflows: ["Create Ouitoulia Release"]
    branches:
      - '10.1.x'
      - '10.2.x'
      - '10.3.x'
    types:
      - completed

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 1.x

      - name: Fixup git permissions
        # https://github.com/actions/checkout/issues/766
        shell: bash
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Get Ouitoulia latest version
        id: data
        run: |
          echo "ouitoulia_tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
        shell: bash

      - name: Fix version in Dockerfile
        run: |
          # Modifico la versione nel Dockerfile con ${{ env.ouitoulia_tag }}
          sed -i "s/ENV OUITOULIA_VERSION .*/ENV OUITOULIA_VERSION ${{ env.ouitoulia_tag }}/" Dockerfile
          git add Dockerfile
          git commit -m "Update Dockerfile version ${{ env.ouitoulia_tag }}"
          git push origin
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish
        run: |
          docker login -u ouitoulia -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker buildx create --use
          docker buildx build --provenance=true --sbom=true -t ouitoulia/naus-emporos:latest --push .
        shell: bash
